### ISSUE TITLE
Getting error running your code

### ISSUE THREAD

**Issue by GreenwichDairy** [h5p9sl/hmac_sha256#1]
Hi,
Thanks vm for posting this code. When I compiled and ran your code (had to make a small adjustment in concat_and_hash:
    uint8_t* buf;
    buf = calloc(destlen + srclen, sizeof(uint8_t));
it compiles and works, but the assert throws an error:
Message: Hello World!
HMAC: acde3f64ec328ad72d496afcc86de01509eac15505a4517471b6ed47d1b218dd
Assertion failed: ss_result.str() == "4b393abced1c497f8048860ba1ede46a23f1ff5209b18e9c428bddfbb690aad8", file C:\dev\HMACTest\HMACTest.cpp, line 43

Do you have any idea   what is causing this?
Thanks
Jerome

**Comment by h5p9sl** [comment]
Hey Jerome,
I took a look and found that the cause of the issue was simply due to the fact that you changed `buf` from a `uint8_t[]` to `uint8_t*`, which caused issues with the `SIZEOFARRAY` macro _(`sizeof(uint8*)` isn't equal to `sizeof(uint8[32])`)_.

Essentially, you accidentally truncated the data while passing it into sha256, which resulted in an invalid result.

Here's a fix to the issue:
```diff
 static void concat_and_hash(const void *dest, const unsigned destlen,
         const void *src, const unsigned srclen,
         void *out, const unsigned outlen) {
+    const unsigned buflen = destlen + srclen;
     uint8_t hash[SHA256_HASH_SIZE];
-    uint8_t buf[destlen + srclen];
+    uint8_t* buf;
+    buf = (uint8_t*)calloc(buflen, sizeof(uint8_t));

     memcpy(buf, dest, destlen);
     memcpy(buf + destlen, src, srclen);

     // Hash 'buf' and store into into another buffer
-    sha256(buf, SIZEOFARRAY(buf), hash);
+    sha256(buf, buflen * sizeof(uint8_t), hash);

     // Copy the resulting hash to the output buffer
     // Truncate hash if needed
```

Thanks for taking the time to create an issue, I'm always happy to help if you need anything else! :+1:

**Comment by GreenwichDairy** [comment]
Hi Tyler

 

That indeed fixed the problem!

Thank you for the quick reply. You’ve been a great help. Your code is so much simpler than implementing CryptoPP, which I finally got to work as well.

 

Thanks vm

Jerome
