### ISSUE TITLE
Issue with hmac_sha256.c

### ISSUE THREAD

**Issue by dvd280** [h5p9sl/hmac_sha256#3]
Hi, thanks for posting your code. When trying to compile I noticed that  the `hmac_sha256.c` file has a problem in the function definition at line 76:

    const size_t buflen = xlen + ylen;
    uint8_t buf[buflen];

 buflen is not a real const, or at least that's how the visual studio compiler sees it.

**Comment by h5p9sl** [comment]
Hey,
Thank you for opening the issue. This is a bit of a strange issue because according to the MSVC documentation, The `const` keyword is used correctly here.

However, after a bit of digging I'm pretty sure the real issue is due to `buf` being a Variable Length Array<sup>[[1]](https://en.cppreference.com/w/c/language/array#Variable-length_arrays)</sup> and MSVC not supporting them<sup>[[2]](https://docs.microsoft.com/en-us/cpp/cpp/arrays-cpp?view=msvc-160#stack-declarations)</sup>. Hence why the compiler might complain that `buflen` is not static.

A simple fix to the issue is to use `malloc` to allocate `buf`:
```diff
  const size_t buflen = xlen + ylen;
- uint8_t buf[buflen];
+ uint8_t* buf = calloc(buflen, sizeof(uint8_t));
...
+ free(buf);
```
I'll probably change the code in a while to reflect this.

Again, thank you for opening an issue. Let me know if there's anything else. :+1:
